image: gitlab/dind
services:
  - docker:dind

variables:
  USER_GITLAB: sanjaybsm
  APP_NAME: poc-ci

stages:
  - build
  - test

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn clean package -B"
  artifacts:
    paths:
      - target/*.jar

maven-test:
  image: maven:3-jdk-11
  stage: test
  script: "mvn test"
  artifacts:
    paths:
      - target/*.jar
